package com.school.school.entity;
// Generated Dec 21, 2019 1:36:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name="course"
    ,catalog="school_db"
)
public class
Course  implements java.io.Serializable {


     private Long id;
     private String name;
     private String status;
     private Date startDate;
     private Date endDate;
     private Set<RoomCourseSchedule> roomCourseSchedules = new HashSet<RoomCourseSchedule>(0);

    public Course() {
    }

	
    public Course(String name) {
        this.name = name;
    }
    public Course(String name, String status, Date startDate, Date endDate, Set<RoomCourseSchedule> roomCourseSchedules) {
       this.name = name;
       this.status = status;
       this.startDate = startDate;
       this.endDate = endDate;
       this.roomCourseSchedules = roomCourseSchedules;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=50 ,unique = true)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="status", length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="start_date", length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="end_date", length=10)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="course")
    public Set<RoomCourseSchedule> getRoomCourseSchedules() {
        return this.roomCourseSchedules;
    }
    
    public void setRoomCourseSchedules(Set<RoomCourseSchedule> roomCourseSchedules) {
        this.roomCourseSchedules = roomCourseSchedules;
    }




}


