package com.school.school.entity;
// Generated Dec 21, 2019 1:36:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * CourseSubject generated by hbm2java
 */
@Entity
@Table(name="course_subject"
    ,catalog="school_db"
)
public class CourseSubject  implements java.io.Serializable {

     private Long id;
     private long subjectId;
     private long courseId;
     private String status;
     private Date dateAdded;

    public CourseSubject() {
    }

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name="subject_id", nullable=false)
    public long getSubjectId() {
        return this.subjectId;
    }

    public void setSubjectId(long subjectId) {
        this.subjectId = subjectId;
    }

    @Column(name="course_id", nullable=false)
    public long getCourseId() {
        return this.courseId;
    }

    public void setCourseId(long courseId) {
        this.courseId = courseId;
    }

    @Column(name="status", nullable=false, length=20)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_added", length=10)
    public Date getDateAdded() {
        return this.dateAdded;
    }

    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }

}


