package com.school.school.entity;
// Generated Dec 21, 2019 1:36:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Room generated by hbm2java
 */
@Entity
@Table(name="room"
    ,catalog="school_db"
)
public class Room  implements java.io.Serializable {


     private Long id;
     private String name;
     private String status;
     private Set<RoomCourseSchedule> roomCourseSchedules = new HashSet<RoomCourseSchedule>(0);

    public Room() {
    }

	
    public Room(String name, String status) {
        this.name = name;
        this.status = status;
    }
    public Room(String name, String status, Set<RoomCourseSchedule> roomCourseSchedules) {
       this.name = name;
       this.status = status;
       this.roomCourseSchedules = roomCourseSchedules;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=50 , unique = true)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="status", nullable=false, length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="room")
    public Set<RoomCourseSchedule> getRoomCourseSchedules() {
        return this.roomCourseSchedules;
    }
    
    public void setRoomCourseSchedules(Set<RoomCourseSchedule> roomCourseSchedules) {
        this.roomCourseSchedules = roomCourseSchedules;
    }




}


