package com.school.school.entity;
// Generated Sep 15, 2020 1:27:48 AM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Subscription generated by hbm2java
 */
@Entity
@Table(name="subscription"
    ,catalog="fitness_factory"
)
public class Subscription  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String status;
//     private Set<User> users = new HashSet<User>(0);

    public Subscription() {
    }

    public Subscription(Integer id, String name, String status) {
        this.id = id;
        this.name = name;
        this.status = status;
    }

    public Subscription(String status) {
        this.status = status;
    }
    public Subscription(String name, String status, Set<User> users) {
       this.name = name;
       this.status = status;
//       this.users = users;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="status", nullable=false, length=10)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

//@OneToMany(fetch=FetchType.LAZY, mappedBy="subscription")
//    public Set<User> getUsers() {
//        return this.users;
//    }

//    public void setUsers(Set<User> users) {
//        this.users = users;
//    }




}


