package com.school.school.entity;
// Generated Dec 21, 2019 1:36:33 PM by Hibernate Tools 4.3.1


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * UserCourse generated by hbm2java
 */
@Entity
@Table(name = "user_course"
        , catalog = "school_db"
)
public class UserCourse implements java.io.Serializable {

    private Long id;
    private long courseId;
    private long userId;
    private String status;

    public UserCourse() {
    }

    public UserCourse(long courseId, long userId, String status) {
        this.courseId = courseId;
        this.userId = userId;
        this.status = status;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "course_id", unique = true, nullable = false)
    public long getCourseId() {
        return this.courseId;
    }

    public void setCourseId(long courseId) {
        this.courseId = courseId;
    }


    @Column(name = "user_id", nullable = false)
    public long getUserId() {
        return this.userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }


    @Column(name = "status", nullable = false, length = 20)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }


}


